server:
  port: 8763

spring:
  application:
    name: short_link_app
  mvc:
    static-path-pattern: /static/**
  redis:
    host: 127.0.0.1
    port: 6379
  jackson:
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/short_link?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 30
      auto-commit: true
      idle-timeout: 500000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 60000
      connection-test-query: SELECT 1

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml

short:
  link:
    # 本地缓存最大数量
    localCacheMaxSize: 10
    # 本地缓存过期时间，单位：毫秒
    localCacheExpire: 600000  # 10分钟
    # 短链接解析域名
    domain: http://127.0.0.1:8763